name = "bkd-website"
main = "src/index.ts"
compatibility_date = "2026-03-15"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "bkd-releases"

[env.production]
routes = [
  { pattern = "bkd.bk.io", custom_domain = true }
]

[[env.production.r2_buckets]]
binding = "RELEASES"
bucket_name = "bkd-releases"
